package com.studyasist.notification

const val CHANNEL_ID = "study_reminder"
const val CHANNEL_NAME = "Study Reminder"
const val CHANNEL_ID_ALARM = "study_reminder_alarm"
const val CHANNEL_NAME_ALARM = "Study reminder alarm"
const val CHANNEL_ID_ALARM_TTS = "study_reminder_alarm_tts"
const val CHANNEL_NAME_ALARM_TTS = "Study reminder (custom message)"
const val ACTION_SHOW_REMINDER = "com.studyasist.SHOW_REMINDER"
const val ACTION_DISMISS_ALARM_TTS = "com.studyasist.DISMISS_ALARM_TTS"

const val EXTRA_ACTIVITY_ID = "activity_id"
const val WORK_INPUT_ACTIVITY_ID = "activity_id"
const val EXTRA_TIMETABLE_ID = "timetable_id"
const val EXTRA_TIMETABLE_NAME = "timetable_name"
const val EXTRA_TITLE = "title"
const val EXTRA_BODY = "body"
const val EXTRA_DAY_OF_WEEK = "day_of_week"
const val EXTRA_ALARM_TTS_MESSAGE = "alarm_tts_message"
const val EXTRA_SOUND_ENABLED = "sound_enabled"
const val EXTRA_USE_SPEECH_SOUND = "use_speech_sound"
const val EXTRA_FROM_TTS_SERVICE = "from_tts_service"
const val EXTRA_TTS_VOICE_NAME = "tts_voice_name"